# Generated by Django 4.0.5 on 2022-06-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authoring_customer_executor_message_order_ordering_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service_type',
            new_name='order_type',
        ),
    ]
